# - name: app setup
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: app-setup

# - name: nodejs
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: nodejs

# - name: mongodb setup
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: mongodb-setup

# - name: systemctl service
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: systemd


- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml
