- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: check cities schema exists or not
  ansible.builtin.command:  mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: print output
  ansible.builtin.debug:
    msg: "schema output: {{schema}}"


- name: Ensure /app/schema directory exists
  ansible.builtin.file:
    path: /app/schema
    state: directory
    mode: '0755'

- name: Copy shipping schema file
  ansible.builtin.copy:
    src: files/shipping.sql       # relative to your playbook's "files/" dir
    dest: /app/schema/shipping.sql
    mode: '0644'

- name: load cities data
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
  when: schema.stdout != "1"