- name: Install python packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel

- name: Install dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3
